apiVersion: v1
kind: Template
metadata:
  name: kafka-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: kafka-secrets
    labels:
      app: "${APP_NAME}"
  stringData:
    hostname: "${MESSAGING_HOSTNAME}"
    password: "${MESSAGING_PASSWORD}"
    username: "${MESSAGING_USERNAME}"
parameters:
- name: APP_NAME
  description: The name that the application will be deployed as in OpenShift.  Used to group OpenShift objects.
  value: manageiq
- name: MESSAGING_HOSTNAME
  description: The hostname that the application will use to connect to the messaging server
  value: kafka
- name: MESSAGING_PASSWORD
  description: The password that the application will use to conect to the messaging server
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: MESSAGING_USERNAME
  description: The database user that the application will use to conect to the messaging server
  value: root
