apiVersion: v1
kind: Template
metadata:
  name: postgresql-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql-secrets
    labels:
      app: "${APP_NAME}"
  stringData:
    dbname: "${DATABASE_NAME}"
    hostname: "${DATABASE_HOSTNAME}"
    password: "${DATABASE_PASSWORD}"
    username: "${DATABASE_USER}"
    port: "${DATABASE_PORT}"
parameters:
- name: APP_NAME
  description: The name of that the application will be deployed as in OpenShift.  Used to group OpenShift objects.
  value: manageiq
- name: DATABASE_HOSTNAME
  description: The hostname that the application will use to connect to the Postgres server
  value: postgresql
- name: DATABASE_NAME
  description: The name of the Postgres database that the application will use to store its data
  value: vmdb_production
- name: DATABASE_PASSWORD
  description: The password that the application will use to conect to the Postgres server
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: DATABASE_USER
  description: The database user that the application will use to conect to the Postgres server
  value: root
- name: DATABASE_PORT
  description: The TCP port that the Postgres listens on for incoming connections
  value: '5432'
