apiVersion: v1
kind: Template
metadata:
  name: manageiq-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql-secrets
    labels:
      app: manageiq
  stringData:
    hostname: "${DATABASE_HOSTNAME}"
    password: "${DATABASE_PASSWORD}"
    username: "${DATABASE_USER}"
    dbname: "${DATABASE_NAME}"
- apiVersion: v1
  kind: Secret
  metadata:
    name: manageiq-secrets
    labels:
      app: manageiq
  stringData:
    admin-password: "${APPLICATION_ADMIN_PASSWORD}"
    v2-key: "${V2_KEY}"
parameters:
- name: APPLICATION_ADMIN_PASSWORD
  value: smartvm
- name: DATABASE_HOSTNAME
  value: postgresql
- name: DATABASE_NAME
  value: vmdb_production
- name: DATABASE_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: DATABASE_USER
  value: root
- name: V2_KEY
  from: "[a-zA-Z0-9]{43}"
  generate: expression
