apiVersion: v1
kind: Template
metadata:
  name: manageiq-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: manageiq-secrets
    labels:
      app: manageiq
  stringData:
    pg-password: ${DATABASE_PASSWORD}
    admin-password: ${APPLICATION_ADMIN_PASSWORD}
    database-url: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_SERVICE_NAME}/${DATABASE_NAME}?encoding=utf8&pool=5&wait_timeout=5
    v2-key: ${V2_KEY}
parameters:
- name: APPLICATION_ADMIN_PASSWORD
  value: smartvm
- name: DATABASE_SERVICE_NAME
  value: postgresql
- name: DATABASE_USER
  value: root
- name: DATABASE_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: DATABASE_NAME
  value: vmdb_production
- name: V2_KEY
  from: "[a-zA-Z0-9]{43}"
  generate: expression
