apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manageiq-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  - clusterroles
  - roles
  verbs:
  - escalate
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - manageiq-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - manageiq.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cache.example.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - manageiq.org
  resources:
  - '*'
  - manageiqs
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - '*'
